name: gaa-kickout
channels:
- conda-forge
- defaults
- https://repo.anaconda.com/pkgs/main
- https://repo.anaconda.com/pkgs/r
dependencies:
- _libgcc_mutex=0.1=main
- _openmp_mutex=5.1=1_gnu
- bzip2=1.0.8=h5eee18b_6
- ca-certificates=2025.7.14=hbd8a1cb_0
- expat=2.7.1=h6a678d5_0
- ld_impl_linux-64=2.40=h12ee557_0
- libffi=3.4.4=h6a678d5_1
- libgcc-ng=15.1.0=h69a702a_3
- libgcc=15.1.0=h767d61c_3
- libgomp=15.1.0=h767d61c_3
- libstdcxx-ng=15.1.0=h4852527_3
- libstdcxx=15.1.0=h8f9b012_3
- libuuid=1.41.5=h5eee18b_0
- libxcb=1.17.0=h9b100fa_0
- ncurses=6.4=h6a678d5_0
- openssl=3.5.1=h7b32b05_0
- pip=25.1=pyhc872135_2
- pthread-stubs=0.3=h0ce48e5_1
- python=3.11.13=h1a3bd86_0
- readline=8.2=h5eee18b_0
- setuptools=78.1.1=py311h06a4308_0
- sqlite=3.45.3=h5eee18b_0
- tk=8.6.14=h993c535_1
- wheel=0.45.1=py311h06a4308_0
- xorg-libx11=1.8.12=h9b100fa_1
- xorg-libxau=1.0.12=h9b100fa_0
- xorg-libxdmcp=1.1.5=h9b100fa_0
- xorg-xorgproto=2024.1=h5eee18b_1
- xz=5.6.4=h5eee18b_1
- zlib=1.2.13=h5eee18b_1
- pip:
  - absl-py==2.3.0
  - addict==2.4.0
  - aiofiles==24.1.0
  - aiohappyeyeballs==2.6.1
  - aiohttp-retry==2.8.3
  - aiohttp==3.10.11
  - aioice==0.10.1
  - aiortc==1.9.0
  - aiosignal==1.3.2
  - aiosqlite==0.21.0
  - albumentations==1.3.1
  - annotated-types==0.7.0
  - anthropic==0.49.0
  - antlr4-python3-runtime==4.9.3
  - anyio==4.9.0
  - apscheduler==3.11.0
  - asyncua==1.1.6
  - attrs==25.3.0
  - av==12.3.0
  - awscli==1.36.40
  - backoff==2.2.1
  - beautifulsoup4==4.13.4
  - boto3==1.35.60
  - botocore==1.35.99
  - boxmot==13.0.6
  - cachetools==5.5.2
  - certifi==2025.4.26
  - cffi==1.17.1
  - charset-normalizer==3.4.2
  - click==8.1.8
  - cmake==3.25.0
  - colorama==0.4.6
  - coloredlogs==15.0.1
  - contourpy==1.3.2
  - cryptography==45.0.4
  - cycler==0.12.1
  - cython==3.0.12
  - dataclasses-json==0.6.7
  - decord==0.6.0
  - deepdiff==8.5.0
  - defusedxml==0.7.1
  - distro==1.9.0
  - dnspython==2.7.0
  - docker==7.1.0
  - docutils==0.16
  - einops==0.8.1
  - fastapi==0.110.3
  - filelock==3.17.0
  - filetype==1.2.0
  - filterpy==1.4.5
  - flake8==7.2.0
  - flatbuffers==25.2.10
  - fonttools==4.58.2
  - frozenlist==1.7.0
  - fsspec==2025.5.1
  - ftfy==6.3.1
  - future==1.0.0
  - gdown==5.2.0
  - gitdb==4.0.12
  - gitpython==3.1.44
  - google-ai-generativelanguage==0.6.15
  - google-api-core==2.25.1
  - google-api-python-client==2.176.0
  - google-auth-httplib2==0.2.0
  - google-auth==2.40.3
  - google-crc32c==1.7.1
  - google-generativeai==0.8.5
  - googleapis-common-protos==1.70.0
  - grpcio-status==1.71.2
  - grpcio==1.73.0
  - h11==0.16.0
  - h5py==3.14.0
  - hf-xet==1.1.3
  - httpcore==1.0.9
  - httplib2==0.22.0
  - httpx==0.28.1
  - huggingface-hub==0.32.4
  - humanfriendly==10.0
  - hydra-core==1.3.2
  - idna==3.7
  - ifaddr==0.2.0
  - imageio==2.37.0
  - inference==0.50.4
  - iniconfig==2.1.0
  - iopath==0.1.10
  - isort==6.0.1
  - jinja2==3.1.6
  - jiter==0.10.0
  - jmespath==1.0.1
  - joblib==1.5.1
  - kiwisolver==1.4.8
  - lapx==0.5.11.post1
  - lazy-loader==0.4
  - lit==15.0.7
  - loguru==0.7.3
  - markdown-it-py==3.0.0
  - markdown==3.8
  - markupsafe==3.0.2
  - marshmallow==3.26.1
  - matplotlib==3.10.3
  - mccabe==0.7.0
  - mdurl==0.1.2
  - monai==1.4.0
  - mpmath==1.3.0
  - multidict==6.4.4
  - mypy-extensions==1.1.0
  - networkx==3.5
  - ninja==1.11.1.4
  - numpy==1.26.4
  - nvidia-cublas-cu12==12.6.4.1
  - nvidia-cuda-cupti-cu12==12.6.80
  - nvidia-cuda-nvrtc-cu12==12.6.77
  - nvidia-cuda-runtime-cu12==12.6.77
  - nvidia-cudnn-cu12==9.5.1.17
  - nvidia-cufft-cu12==11.3.0.4
  - nvidia-cufile-cu12==1.11.1.6
  - nvidia-curand-cu12==10.3.7.77
  - nvidia-cusolver-cu12==11.7.1.2
  - nvidia-cusparse-cu12==12.5.4.2
  - nvidia-cusparselt-cu12==0.6.3
  - nvidia-ml-py==12.575.51
  - nvidia-nccl-cu12==2.26.2
  - nvidia-nvjitlink-cu12==12.6.85
  - nvidia-nvtx-cu12==12.6.77
  - omegaconf==2.3.0
  - onnxruntime-gpu==1.22.0
  - onnxruntime==1.21.1
  - openai==1.85.0
  - opencv-contrib-python==4.10.0.84
  - opencv-python-headless==4.10.0.84
  - opencv-python==4.10.0.84
  - orderly-set==5.4.1
  - outcome==1.3.0.post0
  - packaging==24.2
  - paho-mqtt==1.6.1
  - pandas==2.3.0
  - pillow-heif==0.22.0
  - pillow==11.2.1
  - platformdirs==4.3.8
  - pluggy==1.6.0
  - portalocker==3.2.0
  - prometheus-client==0.22.1
  - prometheus-fastapi-instrumentator==6.0.0
  - propcache==0.3.2
  - proto-plus==1.26.1
  - protobuf==6.31.1
  - psutil==7.0.0
  - py-cpuinfo==9.0.0
  - pyasn1-modules==0.4.2
  - pyasn1==0.6.1
  - pybase64==1.0.2
  - pycocotools==2.0.10
  - pycodestyle==2.13.0
  - pycparser==2.22
  - pydantic-core==2.33.2
  - pydantic-settings==2.7.1
  - pydantic==2.11.5
  - pydot==2.0.0
  - pyee==13.0.0
  - pyflakes==3.3.2
  - pygments==2.19.1
  - pyjwt==2.10.1
  - pylibsrtp==0.12.0
  - pylogix==1.0.5
  - pymodbus==3.8.3
  - pyopenssl==25.1.0
  - pyparsing==3.2.3
  - pysocks==1.7.1
  - pytest==8.4.0
  - python-dateutil==2.9.0.post0
  - python-dotenv==1.0.1
  - pytz==2025.2
  - pyyaml==6.0.2
  - qudida==0.0.4
  - redis==5.0.8
  - regex==2024.11.6
  - requests-file==2.1.0
  - requests-toolbelt==1.0.0
  - requests==2.32.4
  - rich==13.9.4
  - roboflow==1.1.66
  - rsa==4.7.2
  - s3transfer==0.10.4
  - safetensors==0.5.3
  - scikit-image==0.25.2
  - scikit-learn==1.7.0
  - scipy==1.15.3
  - selenium==4.33.0
  - sentry-sdk==2.29.1
  - setproctitle==1.3.6
  - shapely==2.0.7
  - shellingham==1.5.4
  - six==1.17.0
  - slack-sdk==3.33.5
  - smmap==5.0.2
  - sniffio==1.3.1
  - sortedcontainers==2.4.0
  - soupsieve==2.7
  - starlette==0.37.2
  - structlog==24.4.0
  - supervision==0.25.1
  - sympy==1.14.0
  - tabulate==0.9.0
  - tb-nightly==2.20.0a20250610
  - tensorboard-data-server==0.7.2
  - threadpoolctl==3.6.0
  - tifffile==2025.6.1
  - timm==1.0.17
  - tldextract==5.1.3
  - tokenizers==0.21.1
  - torch==2.7.1
  - torchaudio==2.0.2+cu117
  - torchmetrics==0.10.3
  - torchvision==0.22.1
  - tqdm==4.67.1
  - transformers==4.53.2
  - trio-websocket==0.12.2
  - trio==0.30.0
  - triton==3.3.1
  - twilio==9.3.8
  - typer==0.12.5
  - typing-extensions==4.13.2
  - typing-inspect==0.9.0
  - typing-inspection==0.4.1
  - tzdata==2025.2
  - tzlocal==5.3.1
  - ultralytics-thop==2.0.14
  - ultralytics==8.3.155
  - uritemplate==4.2.0
  - urllib3==2.4.0
  - wait-for2==0.3.2
  - wandb==0.20.1
  - wcwidth==0.2.13
  - webdriver-manager==4.0.2
  - websocket-client==1.8.0
  - werkzeug==3.1.3
  - wsproto==1.2.0
  - yacs==0.1.8
  - yapf==0.43.0
  - yarl==1.20.1
  - zxing-cpp==2.2.0
